In [13]:
import numpy as np, pandas as pd,matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("FlightPassengerData.xlsx")

In [3]:
df.head()

num_passengers sales_channel  trip_type  purchase_lead  length_of_stay  \
0               2      Internet  RoundTrip            262              19   
1               1      Internet  RoundTrip            112              20   
2               2      Internet  RoundTrip            243              22   
3               1      Internet  RoundTrip             96              31   
4               2      Internet  RoundTrip             68              22   

   flight_hour flight_day   route booking_origin  wants_extra_baggage  \
0            7        Sat  AKLDEL    New Zealand                    1   
1            3        Sat  AKLDEL    New Zealand                    0   
2           17        Wed  AKLDEL          India                    1   
3            4        Sat  AKLDEL    New Zealand                    0   
4           15        Wed  AKLDEL          India                    1   

   wants_preferred_seat  wants_in_flight_meals  flight_duration  \
0                     0                      0             5.52   
1                     0                      0             5.52   
2                     1                      0             5.52   
3                     0                      1             5.52   
4                     0                      1             5.52   

   booking_complete  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [4]:
data = df[['num_passengers','length_of_stay','purchase_lead','flight_hour','flight_duration']]

In [5]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

In [7]:
data_scaled

array([[ 0.40068439, -0.11935316,  1.95753005, -0.38176438, -1.17417457],
       [-0.57955926, -0.08984361,  0.29916394, -1.12077999, -1.17417457],
       [ 0.40068439, -0.0308245 ,  1.74747034,  1.46577464, -1.17417457],
       ...,
       [-0.57955926, -0.50297735, -0.67374418,  2.38954416, -1.10736752],
       [-0.57955926, -0.50297735, -0.77324614,  0.35725123, -1.10736752],
       [-0.57955926, -0.50297735, -0.72902305,  0.17249733, -1.10736752]])

In [8]:
pca = PCA(n_components=2)
data_pca = pca.fit_transform(data_scaled)

In [10]:
data_pca

array([[-1.58150902,  0.12356929],
       [ 0.02308818, -0.93681486],
       [-1.68188093,  0.21014393],
       ...,
       [-0.13942992, -1.25045085],
       [ 0.19437   , -1.47647203],
       [ 0.196583  , -1.46966277]])

In [9]:
print("Original shape: ", data_scaled.shape)
print("Transformed shape:", data_pca.shape) 

Original shape:  (50000, 5)
Transformed shape: (50000, 2)


In [11]:
pca.explained_variance_

array([1.30152269, 1.11003422])